package hue.captains.singapura.js.homing.demo.workspacewidgets.animals;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The animal choice party's type, as the page has it: {@code ANIMAL_CHOICE},
 * generated from {@link AnimalChoice#TYPE} - so every message is checked
 * against what Java declared.
 */
public record AnimalChoiceModule() implements EsModule<AnimalChoiceModule>, SelfContent {

    public static final AnimalChoiceModule INSTANCE = new AnimalChoiceModule();

    public record ANIMAL_CHOICE() implements Exportable._Constant<AnimalChoiceModule> {}

    @Override public ImportsFor<AnimalChoiceModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<AnimalChoiceModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new ANIMAL_CHOICE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by AnimalChoiceModule from AnimalChoice.TYPE - do not hand-edit.", AnimalChoice.TYPE.js());
    }
}
