package hue.captains.singapura.js.homing.demo.components;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** {@code COMPONENT_CONTROL}: the component-control party type, generated from {@link ComponentControl#TYPE}. */
public record ComponentControlModule() implements EsModule<ComponentControlModule>, SelfContent {

    public static final ComponentControlModule INSTANCE = new ComponentControlModule();

    public record COMPONENT_CONTROL() implements Exportable._Constant<ComponentControlModule> {}

    @Override public ImportsFor<ComponentControlModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ComponentControlModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new COMPONENT_CONTROL())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by ComponentControlModule from ComponentControl.TYPE - do not hand-edit.", ComponentControl.TYPE.js());
    }
}
