package hue.captains.singapura.js.homing.demo.components;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * {@code COMPONENT_DEMO_LOG}: the demo log's party type, generated from {@link ComponentLog#DEMO}. A
 * module of its own, not one with the control log's: an import list keeps one import per module,
 * so two constants of one module could not both be taken by a page that takes them apart.
 */
public record ComponentDemoLogModule() implements EsModule<ComponentDemoLogModule>, SelfContent {

    public static final ComponentDemoLogModule INSTANCE = new ComponentDemoLogModule();

    public record COMPONENT_DEMO_LOG() implements Exportable._Constant<ComponentDemoLogModule> {}

    @Override public ImportsFor<ComponentDemoLogModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ComponentDemoLogModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new COMPONENT_DEMO_LOG())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by ComponentDemoLogModule from ComponentLog.DEMO - do not hand-edit.", ComponentLog.DEMO.js());
    }
}
