package hue.captains.singapura.js.homing.demo.components;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** {@code COMPONENT_CONTROL_LOG}: the control log's party type, generated from {@link ComponentLog#CONTROL}; a module of its own, as the demo log's is. */
public record ComponentControlLogModule() implements EsModule<ComponentControlLogModule>, SelfContent {

    public static final ComponentControlLogModule INSTANCE = new ComponentControlLogModule();

    public record COMPONENT_CONTROL_LOG() implements Exportable._Constant<ComponentControlLogModule> {}

    @Override public ImportsFor<ComponentControlLogModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ComponentControlLogModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new COMPONENT_CONTROL_LOG())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by ComponentControlLogModule from ComponentLog.CONTROL - do not hand-edit.", ComponentLog.CONTROL.js());
    }
}
