package hue.captains.singapura.js.homing.demo.components;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.List;

/**
 * {@code DEMO_DRAWINGS}: the drawings the picture demos show, as data - each an SVG file under
 * {@code demos/drawings/} beside this module, read when served. A drawing is content, as a doc's
 * diagram is: the view that shows it holds no markup of its own and parses what it is handed.
 * Written as JSON strings, every {@code <} escaped as {@code <}, as markup inside a script
 * always is.
 */
public record DemoDrawingsModule() implements EsModule<DemoDrawingsModule>, SelfContent {

    public static final DemoDrawingsModule INSTANCE = new DemoDrawingsModule();

    /** The drawings by name: the drawing's file, without its extension. */
    static final List<String> DRAWINGS = List.of("flow", "stages");

    public record DEMO_DRAWINGS() implements Exportable._Constant<DemoDrawingsModule> {}

    @Override public ImportsFor<DemoDrawingsModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<DemoDrawingsModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new DEMO_DRAWINGS())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        var entries = DRAWINGS.stream().map(name -> quote(name) + ": " + quote(drawing(name))).toList();
        return List.of("// Generated by DemoDrawingsModule from demos/drawings/*.svg - do not hand-edit: the drawings, as data.",
                       "const DEMO_DRAWINGS = Object.freeze({ " + String.join(", ", entries) + " });");
    }

    /** A drawing's markup, as its file has it. */
    String drawing(String name) {
        String path = "demos/drawings/" + name + ".svg";
        try (InputStream in = DemoDrawingsModule.class.getClassLoader().getResourceAsStream(path)) {
            if (in == null) throw new IllegalStateException("DemoDrawingsModule: no drawing at " + path);
            return new String(in.readAllBytes(), StandardCharsets.UTF_8).strip();
        } catch (IOException e) {
            throw new UncheckedIOException(path, e);
        }
    }

    private static String quote(String s) {
        var b = new StringBuilder("\"");
        for (char ch : s.toCharArray()) {
            switch (ch) {
                case '"' -> b.append("\\\"");
                case '\\' -> b.append("\\\\");
                case '\n' -> b.append("\\n");
                case '\r' -> { }
                case '<' -> b.append("\\u003c");
                default -> { if (ch < 0x20) b.append(String.format("\\u%04x", (int) ch)); else b.append(ch); }
            }
        }
        return b.append('"').toString();
    }
}
