package hue.captains.singapura.js.homing.demo.components;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.stream.Collectors;

/**
 * The house's demos, as a page looks them up: {@code HOUSE_DEMOS[leaf]} is the widget that shows a
 * leaf live, by the leaf's token; {@code HOUSE_AROUND} the leaves the page around the demos shows,
 * and where; {@code HOUSE_PENDING} the realized leaves whose demos are still to come, and {@code
 * HOUSE_UNREALIZED} those nothing realizes yet. Generated from {@link HouseDemos}, each class
 * imported from the module that exports it, so no second list can drift from it.
 *
 * <p>A {@code DomModule}, though it touches no DOM: a plain module's imports are served without
 * the page's theme, so the demos it imports - and the parties and the steward they import - would
 * load a second time.</p>
 */
public record HouseDemosModule() implements DomModule<HouseDemosModule>, SelfContent {

    public static final HouseDemosModule INSTANCE = new HouseDemosModule();

    public record HOUSE_DEMOS() implements Exportable._Constant<HouseDemosModule> {}

    public record HOUSE_AROUND() implements Exportable._Constant<HouseDemosModule> {}

    public record HOUSE_PENDING() implements Exportable._Constant<HouseDemosModule> {}

    public record HOUSE_UNREALIZED() implements Exportable._Constant<HouseDemosModule> {}

    @Override
    public ImportsFor<HouseDemosModule> imports() {
        var b = ImportsFor.<HouseDemosModule>builder();
        var classes = new LinkedHashSet<ModuleImports<?>>();
        for (Demo d : HouseDemos.INSTANCE.demos()) classes.add(d.constructs());
        for (ModuleImports<?> c : classes) b.add(c);
        return b.build();
    }

    @Override
    public ExportsOf<HouseDemosModule> exports() {
        return new ExportsOf<>(INSTANCE, List.of(new HOUSE_DEMOS(), new HOUSE_AROUND(), new HOUSE_PENDING(), new HOUSE_UNREALIZED()));
    }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        var house = HouseDemos.INSTANCE;
        String demos = house.demos().stream().map(d -> "\"" + d.leaf().token() + "\": " + d.className()).collect(Collectors.joining(", "));
        String around = house.aroundIt().stream()
                .map(a -> "\"" + a.leaf().token() + "\": \"" + a.where().replace("\\", "\\\\").replace("\"", "\\\"") + "\"")
                .collect(Collectors.joining(", "));
        String pending = house.pending().stream().map(c -> "\"" + c.token() + "\"").collect(Collectors.joining(", "));
        String unrealized = house.unrealized().stream().map(c -> "\"" + c.token() + "\"").collect(Collectors.joining(", "));
        return List.of(
                "// Generated by HouseDemosModule from HouseDemos - do not hand-edit: the widget that shows each leaf live.",
                "const HOUSE_DEMOS = Object.freeze({ " + demos + " });",
                "// Shown by the page around the demos, and where.",
                "const HOUSE_AROUND = Object.freeze({ " + around + " });",
                "// Realized, their demos still to come.",
                "const HOUSE_PENDING = Object.freeze([" + pending + "]);",
                "// Realized by nothing yet.",
                "const HOUSE_UNREALIZED = Object.freeze([" + unrealized + "]);");
    }
}
