package hue.captains.singapura.js.homing.demo.taxonomy;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** {@code NODE_SELECTION}: the node-selection party type, generated from {@link NodeSelection#TYPE}. */
public record NodeSelectionModule() implements EsModule<NodeSelectionModule>, SelfContent {

    public static final NodeSelectionModule INSTANCE = new NodeSelectionModule();

    public record NODE_SELECTION() implements Exportable._Constant<NodeSelectionModule> {}

    @Override public ImportsFor<NodeSelectionModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<NodeSelectionModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new NODE_SELECTION())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by NodeSelectionModule from NodeSelection.TYPE - do not hand-edit.", NodeSelection.TYPE.js());
    }
}
