package hue.captains.singapura.js.homing.demo.taxonomy;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** {@code TAXONOMY_WORKSPACES}: the workbench's kinds and its root parties, generated from {@link TaxonomyWorkbench#SITE}. */
public record TaxonomyWorkspacesModule() implements DomModule<TaxonomyWorkspacesModule>, SelfContent {

    public static final TaxonomyWorkspacesModule INSTANCE = new TaxonomyWorkspacesModule();

    public record TAXONOMY_WORKSPACES() implements Exportable._Constant<TaxonomyWorkspacesModule> {}

    @Override public ImportsFor<TaxonomyWorkspacesModule> imports() { return TaxonomyWorkbench.SITE.manifestsImports(); }

    @Override
    public ExportsOf<TaxonomyWorkspacesModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new TAXONOMY_WORKSPACES())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by TaxonomyWorkspacesModule from TaxonomyWorkbench.SITE - do not hand-edit: the workbench's kinds, and its root parties.",
                       TaxonomyWorkbench.SITE.manifestsJs("TAXONOMY_WORKSPACES"));
    }
}
