package hue.captains.singapura.js.homing.demo.taxonomy;

import hue.captains.singapura.js.homing.component.taxonomy.Component;
import hue.captains.singapura.js.homing.component.taxonomy.ComponentBranch;
import hue.captains.singapura.js.homing.component.taxonomy.ComponentNode;
import hue.captains.singapura.js.homing.component.taxonomy.ExtentAxis;
import hue.captains.singapura.js.homing.component.taxonomy.Part;
import hue.captains.singapura.js.homing.component.taxonomy.Role;
import hue.captains.singapura.js.homing.component.taxonomy.RoleBranch;
import hue.captains.singapura.js.homing.component.taxonomy.RoleCatalogue;
import hue.captains.singapura.js.homing.component.taxonomy.RoleNode;
import hue.captains.singapura.js.homing.component.taxonomy.RoleRoot;
import hue.captains.singapura.js.homing.component.taxonomy.Root;
import hue.captains.singapura.js.homing.component.taxonomy.Taxon;
import hue.captains.singapura.js.homing.component.taxonomy.Taxonomy;
import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.design.Target;
import hue.captains.singapura.js.homing.design.Trees;
import hue.captains.singapura.js.homing.ui.taxonomy.HouseTaxonomy;

import java.util.ArrayList;
import java.util.List;

/**
 * {@code TAXONOMY}: the house's taxonomy as the widgets read it, written when served - every
 * node by its token, what it is - the root, a branch, a component, a part - where the tree places it and what is under it, how it falls
 * back; a component's parts and where it plays a role in another; a part's owner, base, role and
 * how many; the target leaves, whose product with the nodes is every semantic class; and the role
 * catalogue - its branches, its roles, and every part that names each. Every node of both trees comes
 * with its meaning, and a node of the tree with the axes it varies along by degree - a part, its
 * base's - and those it declares itself.
 */
public record TaxonomyDataModule() implements EsModule<TaxonomyDataModule>, SelfContent {

    public static final TaxonomyDataModule INSTANCE = new TaxonomyDataModule();

    public record TAXONOMY() implements Exportable._Constant<TaxonomyDataModule> {}

    @Override public ImportsFor<TaxonomyDataModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<TaxonomyDataModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new TAXONOMY())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by TaxonomyDataModule from the house's taxonomy, read - do not hand-edit.",
                       "const TAXONOMY = Object.freeze(" + json(HouseTaxonomy.INSTANCE.read(), Trees.targetLeaves()) + ");");
    }

    /** The taxonomy and the targets, as the page is handed them. */
    static String json(Taxonomy t, List<Target> targets) {
        var nodes = new ArrayList<String>();
        for (ComponentNode n : t.nodes()) nodes.add(node(t, n));
        var targetTokens = targets.stream().map(x -> quote(x.token())).toList();
        return "{\"root\":" + quote(Root.INSTANCE.token())
             + ",\"nodes\":[" + String.join(",", nodes) + "]"
             + ",\"targets\":[" + String.join(",", targetTokens) + "]"
             + ",\"axes\":{" + String.join(",", java.util.Arrays.stream(ExtentAxis.values())
                     .map(a -> quote(a.name().toLowerCase(java.util.Locale.ROOT)) + ":" + a.rest()).toList()) + "}"
             + ",\"catalogue\":" + catalogue(t) + "}";
    }

    private static String node(Taxonomy t, ComponentNode n) {
        var b = new StringBuilder("{");
        b.append("\"id\":").append(quote(n.token()));
        b.append(",\"is\":").append(quote(switch (n) {
            case Root r -> "root";
            case ComponentBranch br -> "branch";
            case Component<?> c -> "component";
            case Part<?, ?> p -> "part";
        }));
        b.append(",\"name\":").append(quote(n instanceof Part<?, ?> p ? simple(p.role()) : simple(n)));
        b.append(",\"parent\":").append(switch (n) {
            case Root r -> "null";
            case ComponentBranch br -> quote(t.parent(br).token());
            case Component<?> c -> quote(c.parent().token());
            case Part<?, ?> p -> quote(p.owner().token());
        });
        b.append(",\"children\":").append(tokens(switch (n) {
            case ComponentBranch br -> new ArrayList<ComponentNode>(t.children(br));
            case Component<?> c -> new ArrayList<ComponentNode>(t.partsOf(c));
            case Part<?, ?> p -> List.<ComponentNode>of();
        }));
        b.append(",\"fallback\":").append(tokens(t.fallback(n)));
        b.append(",\"extents\":").append(axes(t.extents(n)));
        if (n instanceof Taxon x) {
            b.append(",\"declares\":").append(axes(x.extents()));
            b.append(",\"meaning\":").append(quote(t.meaning(x).markdown()));
        }
        if (n instanceof Component<?> c) {
            b.append(",\"playedIn\":").append(tokens(t.parts().stream().filter(p -> p.base().equals(c)).map(p -> (ComponentNode) p).toList()));
        }
        if (n instanceof Part<?, ?> p) {
            b.append(",\"owner\":").append(quote(p.owner().token()));
            b.append(",\"base\":").append(quote(p.base().token()));
            b.append(",\"role\":").append(quote(simple(p.role())));
            b.append(",\"roleId\":").append(quote(p.role().name().value()));
            b.append(",\"count\":").append(quote(p.cardinality().multiplicity()));
        }
        return b.append("}").toString();
    }

    /** The role catalogue: its root, its branches by level, its roles - each by its name, unique across it - and a role's uses. */
    private static String catalogue(Taxonomy t) {
        RoleCatalogue c = t.catalogue();
        var nodes = new ArrayList<String>();
        nodes.add(roleNode(t, c, RoleRoot.INSTANCE));
        for (RoleBranch b : c.branches()) nodes.add(roleNode(t, c, b));
        for (Role<?> r : c.roles()) nodes.add(roleNode(t, c, r));
        return "{\"root\":" + quote(RoleRoot.INSTANCE.name().value()) + ",\"nodes\":[" + String.join(",", nodes) + "]}";
    }

    private static String roleNode(Taxonomy t, RoleCatalogue c, RoleNode n) {
        var b = new StringBuilder("{");
        b.append("\"id\":").append(quote(n.name().value()));
        b.append(",\"is\":").append(quote(n instanceof RoleRoot ? "root" : n instanceof RoleBranch ? "branch" : "role"));
        b.append(",\"name\":").append(quote(simple(n)));
        RoleBranch parent = c.parent(n);
        b.append(",\"meaning\":").append(quote(c.meaning(n).markdown()));
        b.append(",\"parent\":").append(parent == null ? "null" : quote(parent.name().value()));
        if (n instanceof RoleBranch branch) {
            b.append(",\"level\":").append(branch.level());
            b.append(",\"children\":[").append(String.join(",", c.children(branch).stream().map(x -> quote(x.name().value())).toList())).append("]");
        }
        if (n instanceof Role<?> role) {
            b.append(",\"children\":[]");
            b.append(",\"uses\":").append(tokens(t.partsNaming(role)));
        }
        return b.append("}").toString();
    }

    /** Axes by their names: {@code ["size","colour"]}. */
    private static String axes(List<ExtentAxis> axes) {
        return "[" + String.join(",", axes.stream().map(a -> quote(a.name().toLowerCase(java.util.Locale.ROOT))).toList()) + "]";
    }

    private static String tokens(List<? extends ComponentNode> nodes) {
        return "[" + String.join(",", nodes.stream().map(x -> quote(x.token())).toList()) + "]";
    }

    private static String simple(Object o) { return o.getClass().getSimpleName(); }

    private static String quote(String s) {
        var b = new StringBuilder("\"");
        for (char ch : s.toCharArray()) {
            switch (ch) {
                case '"' -> b.append("\\\"");
                case '\\' -> b.append("\\\\");
                case '\n' -> b.append("\\n");
                default -> { if (ch < 0x20) b.append(String.format("\\u%04x", (int) ch)); else b.append(ch); }
            }
        }
        return b.append('"').toString();
    }
}
