package hue.captains.singapura.js.homing.demo.taxonomy;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** {@code TAXONOMY_GROUPS}, {@code TAXONOMY_ARRANGEMENTS}: where the workbench is filed and how it is arranged the first time, generated from {@link TaxonomyWorkbench#SITE}. */
public record TaxonomyLayoutModule() implements EsModule<TaxonomyLayoutModule>, SelfContent {

    public static final TaxonomyLayoutModule INSTANCE = new TaxonomyLayoutModule();

    public record TAXONOMY_GROUPS() implements Exportable._Constant<TaxonomyLayoutModule> {}
    public record TAXONOMY_ARRANGEMENTS() implements Exportable._Constant<TaxonomyLayoutModule> {}

    @Override public ImportsFor<TaxonomyLayoutModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<TaxonomyLayoutModule> exports() {
        return new ExportsOf<>(INSTANCE, List.of(new TAXONOMY_GROUPS(), new TAXONOMY_ARRANGEMENTS()));
    }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by TaxonomyLayoutModule from TaxonomyWorkbench.SITE - do not hand-edit.",
                       TaxonomyWorkbench.SITE.groupsJs("TAXONOMY_GROUPS"),
                       TaxonomyWorkbench.SITE.arrangementsJs("TAXONOMY_ARRANGEMENTS"));
    }
}
