package hue.captains.singapura.js.homing.demo.taxonomy;

import hue.captains.singapura.js.homing.component.taxonomy.Component;
import hue.captains.singapura.js.homing.component.taxonomy.ComponentBranch;
import hue.captains.singapura.js.homing.component.taxonomy.ComponentNode;
import hue.captains.singapura.js.homing.component.taxonomy.Part;
import hue.captains.singapura.js.homing.component.taxonomy.Root;
import hue.captains.singapura.js.homing.component.taxonomy.Taxonomy;
import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.design.Target;
import hue.captains.singapura.js.homing.design.Trees;
import hue.captains.singapura.js.homing.ui.taxonomy.HouseTaxonomy;

import java.util.ArrayList;
import java.util.List;

/**
 * {@code TAXONOMY}: the house's taxonomy as the widgets read it, written when served - every
 * node by its token, what it is - the root, a branch, a component, a part - where the tree places it and what is under it, how it falls
 * back; a component's parts and where it plays a role in another; a part's owner, base and role;
 * and the target leaves, whose product with the nodes is every semantic class.
 */
public record TaxonomyDataModule() implements EsModule<TaxonomyDataModule>, SelfContent {

    public static final TaxonomyDataModule INSTANCE = new TaxonomyDataModule();

    public record TAXONOMY() implements Exportable._Constant<TaxonomyDataModule> {}

    @Override public ImportsFor<TaxonomyDataModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<TaxonomyDataModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new TAXONOMY())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by TaxonomyDataModule from the house's taxonomy, read - do not hand-edit.",
                       "const TAXONOMY = Object.freeze(" + json(HouseTaxonomy.INSTANCE.read(), Trees.targetLeaves()) + ");");
    }

    /** The taxonomy and the targets, as the page is handed them. */
    static String json(Taxonomy t, List<Target> targets) {
        var nodes = new ArrayList<String>();
        for (ComponentNode n : t.nodes()) nodes.add(node(t, n));
        var targetTokens = targets.stream().map(x -> quote(x.token())).toList();
        return "{\"root\":" + quote(Root.INSTANCE.token())
             + ",\"nodes\":[" + String.join(",", nodes) + "]"
             + ",\"targets\":[" + String.join(",", targetTokens) + "]}";
    }

    private static String node(Taxonomy t, ComponentNode n) {
        var b = new StringBuilder("{");
        b.append("\"id\":").append(quote(n.token()));
        b.append(",\"is\":").append(quote(switch (n) {
            case Root r -> "root";
            case ComponentBranch br -> "branch";
            case Component<?> c -> "component";
            case Part<?, ?> p -> "part";
        }));
        b.append(",\"name\":").append(quote(n instanceof Part<?, ?> p ? simple(p.role()) : simple(n)));
        b.append(",\"parent\":").append(switch (n) {
            case Root r -> "null";
            case ComponentBranch br -> quote(t.parent(br).token());
            case Component<?> c -> quote(c.parent().token());
            case Part<?, ?> p -> quote(p.owner().token());
        });
        b.append(",\"children\":").append(tokens(switch (n) {
            case ComponentBranch br -> new ArrayList<ComponentNode>(t.children(br));
            case Component<?> c -> new ArrayList<ComponentNode>(t.partsOf(c));
            case Part<?, ?> p -> List.<ComponentNode>of();
        }));
        b.append(",\"fallback\":").append(tokens(t.fallback(n)));
        if (n instanceof Component<?> c) {
            b.append(",\"playedIn\":").append(tokens(t.parts().stream().filter(p -> p.base().equals(c)).map(p -> (ComponentNode) p).toList()));
        }
        if (n instanceof Part<?, ?> p) {
            b.append(",\"owner\":").append(quote(p.owner().token()));
            b.append(",\"base\":").append(quote(p.base().token()));
            b.append(",\"role\":").append(quote(simple(p.role())));
        }
        return b.append("}").toString();
    }

    private static String tokens(List<? extends ComponentNode> nodes) {
        return "[" + String.join(",", nodes.stream().map(x -> quote(x.token())).toList()) + "]";
    }

    private static String simple(Object o) { return o.getClass().getSimpleName(); }

    private static String quote(String s) {
        var b = new StringBuilder("\"");
        for (char ch : s.toCharArray()) {
            switch (ch) {
                case '"' -> b.append("\\\"");
                case '\\' -> b.append("\\\\");
                case '\n' -> b.append("\\n");
                default -> { if (ch < 0x20) b.append(String.format("\\u%04x", (int) ch)); else b.append(ch); }
            }
        }
        return b.append('"').toString();
    }
}
