package hue.captains.singapura.js.homing.demo.workspace;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The demo's workspaces' first states in the split grid, as its page has them:
 * {@code DEMO_ARRANGEMENTS}, by kind, generated from {@link DemoArrangements}
 * through the site ({@code DemoGroups.SITE}) - laid out when the page writes a
 * log that holds nothing yet.
 */
public record DemoArrangementModule() implements EsModule<DemoArrangementModule>, SelfContent {

    public static final DemoArrangementModule INSTANCE = new DemoArrangementModule();

    public record DEMO_ARRANGEMENTS() implements Exportable._Constant<DemoArrangementModule> {}

    @Override public ImportsFor<DemoArrangementModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<DemoArrangementModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new DEMO_ARRANGEMENTS())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by DemoArrangementModule from DemoGroups.SITE - do not hand-edit.",
                DemoGroups.SITE.arrangementsJs("DEMO_ARRANGEMENTS"));
    }
}
