package hue.captains.singapura.js.homing.demo.workspace;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.workspace.shell.GridArrangementJs;

import java.util.List;

/**
 * The demo workspace's first state in the split grid, as its page has it:
 * {@code DEMO_ARRANGEMENT}, generated from {@link DemoArrangements#SPLIT_GRID} -
 * laid out when the page writes a log that holds nothing yet.
 */
public record DemoArrangementModule() implements EsModule<DemoArrangementModule>, SelfContent {

    public static final DemoArrangementModule INSTANCE = new DemoArrangementModule();

    public record DEMO_ARRANGEMENT() implements Exportable._Constant<DemoArrangementModule> {}

    @Override public ImportsFor<DemoArrangementModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<DemoArrangementModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new DEMO_ARRANGEMENT())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by DemoArrangementModule from DemoArrangements.SPLIT_GRID - do not hand-edit.",
                GridArrangementJs.constant("DEMO_ARRANGEMENT", DemoArrangements.SPLIT_GRID));
    }
}
