package hue.captains.singapura.js.homing.demo.workspacewidgets.platformer;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The platformer party's type, as the page has it: {@code PLATFORMER},
 * generated from {@link Platformer#TYPE} - so every message of the run is
 * checked against what Java declared.
 */
public record PlatformerModule() implements EsModule<PlatformerModule>, SelfContent {

    public static final PlatformerModule INSTANCE = new PlatformerModule();

    public record PLATFORMER() implements Exportable._Constant<PlatformerModule> {}

    @Override public ImportsFor<PlatformerModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<PlatformerModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new PLATFORMER())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by PlatformerModule from Platformer.TYPE - do not hand-edit.", Platformer.TYPE.js());
    }
}
